use_frameworks!

platform :ios, '10.0'

target 'YDAuthorizationUtil_Example' do
  pod 'YDAuthorizationUtil', :path => '../'

  target 'YDAuthorizationUtil_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
